#	File MakeFile -  Make instructions for C examples.
#
#	Copyright Apple Computer, Inc. 1986-1995, 1998
#	All rights reserved.
#
#	This makefile builds:
#		The sample application:			Sample
#

# 	You can define {SymOptions} as "-sym on" or "-sym off" for use with SADE
# 	We also recommend requiring prototypes for all functions

SymOptions	=	-sym Full
SymOpt		=	{SymOptions}
COptions	=	-w 17 -proto strict {SymOpt} -D OLDROUTINELOCATIONS=0
MrCOptions	=	{SymOpt} -D OLDROUTINELOCATIONS=0

# The following variable is used to define the ROM map file used by the
# TestPerf component.  If necessary, you can change this to point to the
# proper location of your machine's ROM map.

RomMapLoc	=	{MPW}ROM Maps:
RomMap	  	=	Mac`gestalt mach -s`ROM.map


#######################################################################
# Build instructions and dependencies for the Sample application
#			
#	Sample is an example application that demonstrates how to
#	initialize the commonly used toolbox managers, operate 
#	successfully under MultiFinder, handle desk accessories, 
#	and create, grow, and zoom windows.
#
# 	You can define {SymOptions} as "-sym on" or "-sym off" for use with SADE
# 	We also recommend requiring prototypes for all functions
							
sampObjs	= AIRConfig.c.o

sampLibs	= "{Libraries}"MacRuntime.o ¶
			  "{Libraries}"Interface.o
		
AIRConfig		ÄÄ {sampObjs} AIRConfig.r
	Link -o {Targ} {sampObjs} {sampLibs} {SymOptions}
	Rez -rd -o {Targ} AIRConfig.r -append
	SetFile {Targ} -t APPL -c 'AIRc' -a B
	#Move AIRConfig 'AIRConfig for GlobalTalk'
